import Navbar from '@/components/layout/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import AuthContext from '@/context/AuthContext';
import SWRContext from '@/context/SWRContext';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Vickygram',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={(sans.className, 'w-full max-w-screen-xl overflow-auto mx-auto')}>
        <AuthContext>
          <SWRContext>
            <header className="sticky top-0 bg-white z-10 border-b">
              <Navbar />
            </header>
            <main>{children}</main>
          </SWRContext>
        </AuthContext>
      </body>
    </html>
  );
}
