import Header from '@/components/layout/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Vickygram',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <Header />
        <main className="w-full max-w-screen-2xl m-auto grow mb-20 border h-full text-center">
          {children}
        </main>
      </body>
    </html>
  );
}
